### ISSUE TITLE
repo-us.voidlinux.org certificate expired

### ISSUE THREAD

**Issue by amireh** [void-linux/void-infrastructure#128]
It seems the certificate for https://repo-us.voidlinux.org has expired today and was not renewed in time. This might be similar to #16. This is the output I get on running `xbps-install -S`:

```
[*] Updating repository `https://repo-us.voidlinux.org/current/x86_64-repodata' ...
Certificate verification failed for /CN=*.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://repo-us.voidlinux.org/current/x86_64-repodata': Operation not permitted
[*] Updating repository `https://repo-us.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
Certificate verification failed for /CN=*.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://repo-us.voidlinux.org/current/multilib/nonfree/x86_64-repodata': Operation not permitted
[*] Updating repository `https://repo-us.voidlinux.org/current/multilib/x86_64-repodata' ...
Certificate verification failed for /CN=*.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://repo-us.voidlinux.org/current/multilib/x86_64-repodata': Operation not permitted
[*] Updating repository `https://repo-us.voidlinux.org/current/nonfree/x86_64-repodata' ...
Certificate verification failed for /CN=*.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://repo-us.voidlinux.org/current/nonfree/x86_64-repodata': Operation not permitted
```

Thank you.

**Comment by the-maldridge** [comment]
Most certificates are expired due to a failure of the automatic renewal cronjob that writes them to the shared secret store.  Unfortunately I have been moving house and have not had a chance to get ahead of this problem.  Taking a look now.

**Comment by the-maldridge** [comment]
We're back now.  For reasons I am too tired to debug right now the cert actually renewed a month ago, but the various load balancers across the fleet appear to have never actually picked up the new cert.  I will try to debug this when I have time.

**Comment by amireh** [comment]
I can confirm it's working fine for me now. Your responsiveness is amazing, thank you for fixing this and so quickly.

**Comment by the-maldridge** [comment]
Heh, I had been keeping an eye on this, as had other members of the team.  What concerns me is it happened at all as we have quite a lot of automation to make sure the certs are all renewed and reloaded in all the right places.

**Comment by amireh** [comment]
If it's any consolation, I've had similar pains specifically with the auto-renewal portion of LetsEncrypt issued certificates.

> ... we have quite a lot of automation to ...

And the devil might be right here! :sweat_smile:
