### ISSUE TITLE
[RFC] Replace mediawiki with mdbook

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-infrastructure#14]
Discussion yesterday looked at the idea of replacing the mediawiki with an mdbook repo.  This would simplify the process of updating documentation by using markdown everywhere, and it would mean there would be a single process for mutating the distribution.

I've got a basic shell up of what I think the important sections are at https://michaelwashere.net/scratch/vdocs.  If accepted the rendered documents would be hosted at docs.voidlinux.org.

Approval requested from @Duncaen and @Gottox.
Feedback requested from @void-linux/pkg-committers @shizonic @cameronnemo

**Comment by CameronNemo** [comment]
The outline looks good I think. Under the maintenance section, a subsection on Runit could be added.

**Comment by Gottox** [comment]
I'm not sure what a change in the software is solving. I suspect you're aiming for a better structure.

I can see that our mediawiki is quite messy and a better structure is desirable. What are the measures are taken to improve this pain point and how can we manage the migration?

**Comment by the-maldridge** [comment]
Other measures include review before addition, just like we do for template files, as well as the ability to run automated linting across it before accepting changes.

I am aiming for better structure and ultimately trying to get rid of the database server.

The migration ultimately has to be done by hand in order to ensure that we aren't wasting effort pulling over content that is either obsolete or incomplete.  I believe there is sufficient interest in the community to make this happen, and I'm willing to spearhead the review queue for it to ensure things stay up to date.

**Comment by Vaelatern** [comment]
I like the change in software towards a PR modification approach. We can handle PRs of things that don't look wrong or broken.

**Comment by the-maldridge** [comment]
The decision was made to move forward with mdbook.  Deprecation of the wiki can be discussed separately.
