### ISSUE TITLE
distfiles request: add rtmpdump source tarball

### ISSUE THREAD

**Issue by q66** [void-linux/void-infrastructure#15]
Hi,

for the rtmpdump template in void-packages, the current distfiles URL is dead, and there doesn't seem to be a reliable source for the tarball. Since rtmpdump hasn't really changed since 2015, we should be able to host it in our distfiles location and have the template fetch it from there.

The current tarball is available from https://sources.voidlinux.org/rtmpdump-2.4.20161210/rtmpdump-2.4_p20161210.tar.gz

Relevant PR: void-packages #5967

**Comment by the-maldridge** [comment]
https://alpha.de.repo.voidlinux.org/distfiles/rtmpdump-2.4_p20161210.tar.gz
