### ISSUE TITLE
publish docker images as part of the automation pipeline

### ISSUE THREAD

**Issue by hholst80** [void-linux/void-infrastructure#164]
https://hub.docker.com/u/voidlinux - is this official?

**Comment by classabbyamp** [comment]
all void docker images are hosted on github's ghcr: https://github.com/orgs/void-linux/packages

voidlinux on dockerhub is no longer official

**Comment by hholst80** [comment]
If someone still have access it would be good to mark the repo as deprecated or even better delete it.
