### ISSUE TITLE
alpha.de.repo.voidlinux.org certificate might have expired

### ISSUE THREAD

**Issue by rami3l** [void-linux/void-infrastructure#181]
`xbps-install -y -Su` is failing in my CI. A quick search pointed me to #128:

```
> xbps-install -y -Su
SSL certificate subject doesn't match host alpha.de.repo.voidlinux.org
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
```

**Comment by classabbyamp** [comment]
it was intentionally removed after a deprecation period of over a year:
- https://voidlinux.org/news/2022/05/default-mirror.html
- https://github.com/void-linux/void-infrastructure/commit/454a944820355d8c67809b2851b6e9a7dd87f444

**Comment by classabbyamp** [comment]
looks like you're using the images from dockerhub: https://github.com/rami3l/pacaptr/blob/master/.github/workflows/test.yml#L292

these are no longer updated, see the migration matrix here: https://voidlinux.org/news/2023/08/container-updates.html
