### ISSUE TITLE
South Korean mirror

### ISSUE THREAD

**Issue by youngjinpark20** [void-linux/void-infrastructure#27]
I'm looking to host a South Korean mirror. Currently i have it setup at https://youngjin.io/voidlinux. Currently I have it syncing off of servercentral  every two hours.

**Comment by the-maldridge** [comment]
This got lost in the churn over the last month, @bobertlo can you add this mirror to the docs if it has not already been added?

**Comment by bobertlo** [comment]
@the-maldridge I missed that completely, that's done and I sent a PR to github.io 

https://github.com/void-linux/void-linux.github.io/pull/52

**Comment by the-maldridge** [comment]
Added to docs.
