### ISSUE TITLE
Defunct repos?

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-infrastructure#29]
While working on #28 I noticed that we have several repos that seem to be defunct.  I'd appreciate knowing if these are still repos that we need to keep active.

  * musl-obstack @pullmoll 
  * musl-fts @pullmoll 
  * documentation (obsoleted by infradocs and void-docs)
  * void-installer @Gottox 
  * void-texlive @leahneukirchen 
  * buildbot-config (obsoleted by void-infrastructure)

I'd like to set the repos that we don't intend to use to archived state and revoke all push access from them.

**Comment by pullmoll** [comment]
I don't know what exactly you mean by defunct. The musl-obstack and musl-fts repos are cloned from the ones on my account. They should be kept or perhaps even ownership transferred to void-linux as they are used in some *-musl packages.

**Comment by the-maldridge** [comment]
Defunct as in storing code and not in use.  Since the packages point at your account, I don't really see why there are repos on the organization.  If you think it should be transferred that's fine, I'm just trying to take stock of what's currently setup.

**Comment by pullmoll** [comment]
I think I should transfer them to void-linux. I don't want you to lose the packages in case I drop off the face of the earth some day.

**Comment by leahneukirchen** [comment]
void-texlive is dead, it can be archived or moved to my namespace.

**Comment by the-maldridge** [comment]
@leahneukirchen please move it to your namespace, I will go through and archive some of the repos that are obsolete now.

**Comment by leahneukirchen** [comment]
Forked and archived.

**Comment by pullmoll** [comment]
musl-fts and musl-obstack need to be removed before I can transfer them.

**Comment by the-maldridge** [comment]
@pullmoll moved the repos out of the way, the transfer should be able to go ahead now.

**Comment by pullmoll** [comment]
It is obviously not sufficient to rename them. I still cannot transfer ownership because I get this error `void-linux already has a repository in the pullmoll/musl-obstack network `. Looks like you need to drop the fork.

**Comment by the-maldridge** [comment]
:sigh: I had hoped that GitHubs systems were more elegantly designed than that.  @pullmoll I have now removed the forks entirely.  Sorry for the inconvenience yesterday.  Keep in mind that after you migrate, its plausible that you'll lose access until I can push the team rules again and put access back onto that repo.

**Comment by the-maldridge** [comment]
Closing as obsolete.  The driving reason for repo cleanup has passed.
