### ISSUE TITLE
How to set up my own Tier 2 mirror?

### ISSUE THREAD

**Issue by Wesley-Chan** [void-linux/void-infrastructure#40]
Would you please provide me the instructions to set up one? Thank you.

**Comment by the-maldridge** [comment]
Mirror management discussions happen on IRC, please join #xbps on freenode.

In general mirrors are just rsync, which is beyond the scope of support provided by void-ops.  Mirrors that are non-public are strictly frowned upon unless an agreement is reached w.r.t. use of bandwidth from a tier 1 mirror.
