### ISSUE TITLE
Please update static builds of xbps.

### ISSUE THREAD

**Issue by zayuim** [void-linux/void-infrastructure#46]
Hello, I have noticed that the static builds of xbps (http://alpha.de.repo.voidlinux.org/static/) are quite old. I was hoping that newer versions could continue to be built again.

**Comment by the-maldridge** [comment]
```
xbps-static-static-0.56_5.x86_64-musl.tar.xz       08-Jul-2019 20:33             2991472
```

Looks very up to date to me.  The latest files don't get re-pointed until a release is confirmed to be stable.

**Comment by zayuim** [comment]
Oops sorry. I hadn't checked in a few days. I originally posted this on the xbps repo and was told to post here.

My only complaint now would be to update the "xbps-static-latest" so that they match the new version.
