### ISSUE TITLE
Easier way to check repos for staging

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-infrastructure#48]
Currently the only reliable way to check if a repo is staged, is searching for the last build log that registered a package and check if there is a mention of staging. Just checking the webserver for a $arch-stagedata file is not working, since e.g. the musl repo never has this available.

**Comment by the-maldridge** [comment]
My ideal case would be for a prometheus exporter that could look at
repository status, look at how many packages are
registered/staged/whatever.  We could then easily ingest this data into
the existing monitoring infrastructure and surface it that way.

**Comment by the-maldridge** [comment]
2 years later we have it.  Take a look at the dashboard in the referenced PR and tell me what you think.
