### ISSUE TITLE
xbps-0.57.1_7 out; docker image needs to be updated

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-infrastructure#54]
The xbps package has been updated to revision=7, this includes some critical fixes for updating xbps and xbps-checkvers.

Please update the docker images with new packages, specifically xbps-0.57.1_7!

Thanks

**Comment by the-maldridge** [comment]
Not entirely sure which docker images you want updated, so I'll just update them all.

**Comment by the-maldridge** [comment]
Containers have been rebuilt.  Using them is handled in void-linux/void-packages#18049
