### ISSUE TITLE
docker i686 image needs to be rebuilt

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-infrastructure#55]
Due to this https://github.com/void-linux/void-packages/pull/18049
the docker image still contains an outdated xbps pkg (among others).

See the log:

https://travis-ci.org/void-linux/void-packages/jobs/632881065?utm_medium=notification&utm_source=github_status

Only i686 seems to be affected.

**Comment by the-maldridge** [comment]
The i686 image was bad due to the staged packages from last night.  I've rebuilt it and force pushed on top of the bad tag.
