### ISSUE TITLE
x86_64-musl builder ENOSPC

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-infrastructure#61]
It seems the x86_64-musl builder is out of disk space.
Look at the last lines here https://build.voidlinux.org/builders/x86_64-musl_builder/builds/27129/steps/shell_3/logs/stdio
```
xbps-create: ERROR: cannot write ./usr/lib/debug/usr/lib/liblldb.so.9.0.1 to archive: Write error
```

**Comment by the-maldridge** [comment]
Thanks for raising this, I'll take a look.

**Comment by the-maldridge** [comment]
There is now more space.
