### ISSUE TITLE
Resigned from my own project voidlinux

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-infrastructure#67]
Yes, I decided to resign from my own project "voidlinux".

I resigned from NetBSD as well in 2008, and now I'm resigning from my own project "voidlinux".

I wrote everything related to it, including xbps, xbps-src, void-mklive, void-runit, www. Even so people don't want to treat my comments for good.

Please remove me from everything else xbps. I'm going to move xbps to my own account github account.

I'll let you know when that move is ready, in this case you would be able to remove me.

Cheers

**Comment by xtraeme** [comment]
@Vaelatern I'd like you to know that you are idiot. And you've always been! rofl

**Comment by hippi777** [comment]
hi there! :)

may i ask u why, and whats next? im really new around here, and ive seen 1-2 days ago that some opposition took place, but i didnt think it will escalate to anything serious, and also, i think there was more that happened before, except if ur just tired of the overwhelming amount of things to do... i can clearly see that u have a serious black belt, and it would be really sad to see that u cant resolve whatever problem u have with the others around and leave a huge gap behind urself :/

thx 4 ur time, and all of ur efforts so far now, i really made my research to find The Perfect Fund^TM, and it would be really sad to see it breaking apart just when i arrived, but hey, its not really about me, but common values 1st, and yep, i believe that u r mission critical behind the success of void! :)

but anyhow, i wanna grab the moment to wish all the bests to u, cuz who knows what will come after now...

**Comment by xtraeme** [comment]
what's next? I don't know. But this would mean I'm able to do what I do with MY OWN CODE.

**Comment by hippi777** [comment]
ahh, ive seen actually 2 times of the opposite of that, but yep, i think others should adapt more, while i dunno why they dont, but it would still better to stop for a moment and resolve things instead of set things on fire, i hope now they can see that uve got serious intentions...

**Comment by xtraeme** [comment]
I won't stop. https://github.com/xtraeme/xbps is the MAIN source for #xbps.

**Comment by xtraeme** [comment]
So let this idiots stop using my OWN CODE without ATTRIBUTION.

This is what BSD-2-Clause is about and I'm the code owner.

**Comment by hippi777** [comment]
at least that sounds good :) i couldnt even imagine that u would just install an ubuntu and dont care anymore :D anyways, if i see it right, then theres nothing that would stop u, but then a slow isolation without many flames around would be the best for everyone, and when things will settle, everyone will find their inner peace anyhow...

**Comment by the-maldridge** [comment]
Pre-emptively locking this down as there's a lot of unconstrained emotion in this thread.

Though xtr's behavior towards other project members, uncoordinated pushes to glibc and musl packages, general disregard for breaking users, and other similar actions in the project qualify for immediate removal as a malicious actor.  I believe its in everyone's best interests, including yours xtraeme, to let this sit for a week.

Everyone makes mistakes, and that's okay.  What's not okay is treating peers poorly, snapping at people, and disregard for the ideals of the project.  Lets all take the weekend, enjoy some sun a safe distance from other people, and come back to this next week to see if it is truly the best course of action.

**Comment by the-maldridge** [comment]
Well when I typed that initial response it was under the assumption that calm would prevail.  Due to numerous attacks on project members, we've escalated the situation to GitHub as a breach of platform conduct, and we're proceeding with a project level removal now.
