### ISSUE TITLE
Put xmandump back to work in man.voidlinux.org

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-infrastructure#70]
@Vaelatern recommended I open the issue regarding it here. Is there somewhere I can find the old deployment stuff to help with it?

**Comment by Vaelatern** [comment]
There was no deployment previously. Where is the source for the current binary? Let's start with that and what it wants, then work backwards to give it what it needs.

**Comment by the-maldridge** [comment]
@ericonr you need to package xmandump, then add appropriate config here to run it on snooze as part of the docs playbook.  After that I'll need to deploy the patch, verify that its working, and we'll do a followup change to re-point the DNS name.

**Comment by ericonr** [comment]
@Vaelatern https://github.com/nilium/xmandump/

We'd need to tag a release as well, in order to use it.

**Comment by ericonr** [comment]
Tagged and packaged https://github.com/void-linux/void-packages/pull/22069

**Comment by Vaelatern** [comment]
and it was merged!

**Comment by Vaelatern** [comment]
I'm going to draft some ansible.

**Comment by the-maldridge** [comment]
Resolved by #74
