### ISSUE TITLE
Regeneration of InfraDocs website?

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-infrastructure#71]
Today I came to remove the forum moderation page after chatting to @the-maldridge - only to find it has been removed back in ab55c89a06918983711b54e9d80b5446a7234660!

Could we regenerate the InfraDocs website for this change, and furthermore introduce/fix a hook that auto-regenerates it, like AFAICT is used for the other general void docs?

**Comment by the-maldridge** [comment]
The hook you wish already exists.  I suspect its simply been a while since the code was pushed to the docs server.  I can try this tomorrow to see if that fixes it.

**Comment by the-maldridge** [comment]
Regenerated manually.  Some odd permissions bug is at play here.
