### ISSUE TITLE
popcorn https

### ISSUE THREAD

**Issue by hippi777** [void-linux/void-infrastructure#76]
hi there! :)

1st, i get SSL_ERROR_BAD_CERT_DOMAIN for https://popcorn.voidlinux.org
2nd, when i accept the bad cert, then i get a different page (buildbot) than what http://popcorn.voidlinux.org gives

**Comment by the-maldridge** [comment]
Good Point.  I don't think the popcorn name is currently configured for TLS, so I'll have to take a look into this and get back to you.  Right now my guess would be I just never set it up, but there may have been some deeper problem with it that I'll need to dig into.

**Comment by hippi777** [comment]
i dont hurry nowhere, just met with it randomly... but thx anyway! :)
