### ISSUE TITLE
gitlab presence

### ISSUE THREAD

**Issue by bougyman** [void-linux/void-infrastructure#79]
The https://gitlab.com/voidlinux namespace is reserved, but not used. This should (at the least) mirror https://github.com/void-linux repositories to allow those using gitlab workflows to trigger their pipelines without external calls to github. This is also useful in the case where github has the occasional outage.

**Comment by the-maldridge** [comment]
indeed, having a secondary mirror is a good idea.  I will look into setting this up.

**Comment by Duncaen** [comment]
gitlab.com/void-linux shows 404, but I'm unable to register it, has someone already reserved it?
Might be good to use the same org name.

**Comment by bougyman** [comment]
I agree, and I do think someone already has registered both it an gitlab.com/voidlinux. @the-maldridge If you need any help with the sync to gitlab hit me up in irc. I have experience lifting and shifting that.

**Comment by Vaelatern** [comment]
I have gitlab.com/void-linux

**Comment by the-maldridge** [comment]
Stalled until @Vaelatern has availability.

**Comment by the-maldridge** [comment]
I've filled the paperwork to have the void-linux namespace on gitlab upgraded to the foss gold plan, and once that is complete I can enable mirroring of this repo.  Once that is complete all that will remain is porting the containers to this organization and enabling the builds.

**Comment by NeelChotai** [comment]
looks like the void-packages repo was being mirrored on GitLab but stopped about a year ago, is still interest in this? We could look in to managing [GitLab through Terraform](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_mirror) as well.

**Comment by the-maldridge** [comment]
The original purpose of having the gitlab presence has become defunct as github has replaced this need with native functionality.  I apparently forgot to come back here and update this ticket.
