### ISSUE TITLE
Create runit repo

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-infrastructure#83]
Currently, runit upstream isn't active, and Gerrit Pape hasn't been active on the supervision mailing list for a while. This means that most of our patches in void-packages have a low chance of being upstreamed, and making further changes to it via patches, for purposes such as fixing warnings or weird behavior (this last one is unlikely) gets more confusing each time, since it requires layering patches.

Having a canonical repo for runit makes collaboration and evaluating any changes much easier. We could try to contact Gerrit once the repo is made to see if he wants to pull in changes.

leah2 linked this https://salsa.debian.org/debian/runit/-/tree/master/debian/patches , so there are quite a few opportunities for changes.

@CameronNemo linked https://github.com/nrclark/btrunit

**Comment by the-maldridge** [comment]
I'm okay with this, but if we're going to fork from the upstream, I want to make sure that we're prepared to be a new upstream and not just another unmaintained fork.

**Comment by ericonr** [comment]
My main drive for this is fixing type warnings in compilation, which I quite dislike.

I would be interested in driving those changes, fixing any new warnings that might come up (tooling updates and ...), and integrating any patches that are brought to our attention and that fix actual issues, instead of adding functionality that isn't desired (such as some of the debian stuff).

Making it possible for others to open issues and PRs would also be interesting, as long as we can write a clear policy regarding what's desired for the repo and what isn't. I again would be open to making this effort.

I don't expect runit to require constant maintenance, but I would be willing to maintain this, though obviously with help from other knowledgeable folk who are also interested in it, since it _is_ a very crucial part of most Void systems.

**Comment by the-maldridge** [comment]
Resolved by b19f7cd
