### ISSUE TITLE
Wishlist: extend the man-site role to support multiple repos

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-infrastructure#86]
Besides the arch specific repositories, `xmandump` could go through the `nonfree` packages. This would allow us to display the man pages for utilities such as `nvidia-smi`.

`xmandump` can do multiple repodatas already, so we'd only need to extend the script a bit. I guess the main issue is legality for displaying these pages? Since we already distribute the packages I don't think it would be a huge issue, but I could be missing something.

**Comment by the-maldridge** [comment]
I don't think there's any issue for just showing the man pages, that would be a pretty sorry state of affairs and would likely only be the case for non-redistributable packages like google-chrome or wps-office.  If the script can be extended with minimal effort, then in my opinion this is worth doing.

**Comment by ericonr** [comment]
From a cursory glance, it looked like that was the case. I will open a PR later, then :D

**Comment by the-maldridge** [comment]
I think based on @classabbyamp 's work this is now done.  Can you verify that what you wanted works now @ericonr ?

**Comment by classabbyamp** [comment]
https://man.voidlinux.org/man1/nvidia-smi.1 exists so we can probably close this

**Comment by ericonr** [comment]
Indeed

Sorry for the delay!
