### ISSUE TITLE
Italian mirror

### ISSUE THREAD

**Issue by handow23** [void-linux/void-infrastructure#92]
Hello, a friend of mine would like a closer mirror for Italian users.

We could ask [GARR](http://mirror.garr.it/) (a public computer network) to host one for us. They already mirror PCLinuxOS, Manjaro, Debian, Ubuntu and [others](http://mirror.garr.it/mirrors.html).

Their email for requesting: mirror-service@garr.it

**Comment by the-maldridge** [comment]
@handow23 you are welcome to reach out to any organization near you to request a mirror and refer them back in the direction of Void for assistance in configuring their mirror.
