### ISSUE TITLE
Router Advertisements on c-lej-de are not being accepted

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-infrastructure#96]
The `dhcpcd.conf` of c-lej-de contains `dhcp6`, but the system is meant to be configured using Router Advertisements, and thus gets no IPv6 address.

One can write `ipv6rs` instead of `dhcp6` there, or nothing, because this is the default. But there is no `interface.mode6` to reflect this behavior.

**Comment by the-maldridge** [comment]
The network config has been fixed so that this works correctly now.
